// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230219020807_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnimalBackground")
                        .HasColumnType("longtext");

                    b.Property<string>("AnimalName")
                        .HasColumnType("longtext");

                    b.Property<string>("AnimalType")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalBackground = "six year old white dog",
                            AnimalName = "Izzy",
                            AnimalType = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalBackground = " two year old calico cat",
                            AnimalName = "Random",
                            AnimalType = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalBackground = "one year old long haired black and white cat",
                            AnimalName = "Gremlin",
                            AnimalType = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
